{
    'name': 'Starplastic MRP',
    'version': '1.0.0',
    'category': 'Manufacturing',
    'author': 'Kuldeep Singh',
    'website': '',
    'depends': ['mrp', 'sale_management', 'purchase', 'custom_packing_memo', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/mrp_workcenter_default_shift_data.xml',
        'views/mrp_workcenter_form_views.xml',
        'views/mrp_workcenter_shift_views.xml',
        'views/mrp_production_shift_button_views.xml',
        'views/product_template_views.xml',
        'views/mrp_routing_views.xml',
        'views/mrp_workorder_views.xml',
        'views/mrp_production_hourly_count_button_views.xml',
        'views/mrp_workcenter_hourly_entry_views.xml',
        'views/mrp_job_party_work_views.xml',
        # 'report/report_action.xml',
        # 'report/work_order_report.xml',
        'views/res_company_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
