{
    'name': 'Starplastic MRP',
    'version': '1.0.0',
    'category': 'Manufacturing',
    'author': 'Kuldeep Singh',
    'website': '',
    'depends': ['mrp', 'sale_management', 'purchase', 'custom_packing_memo', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/mrp_workcenter_default_shift_data.xml',
        'views/mrp_workcenter_form_views.xml',
        'views/mrp_workcenter_shift_views.xml',
        'views/mrp_production_shift_button_views.xml',
        'views/product_template_views.xml',
        'views/mrp_routing_views.xml',
        'views/mrp_workorder_views.xml',
        'views/mrp_production_hourly_count_button_views.xml',
        'views/mrp_workcenter_hourly_entry_views.xml',
        'views/mrp_job_party_work_views.xml',
        'views/machine_data_view.xml',
        'report/report_action.xml',
        # 'report/work_order_report.xml',
        'report/rm_loss_report.xml',
        'report/std_cycle_time_report.xml',
        'report/running_cavity_report.xml',
        'report/machine_efficiency_report.xml',
        'report/production_shift_report.xml',
        'report/std_cycle_time_summary.xml',
        'report/running_cavity_summary.xml',
        'views/res_company_views.xml',
        'views/sale_order_line_views.xml',
        'views/production_memo_views.xml',
        'report/error_set_tolerance_report.xml',
        'report/error_set_tolerance_summary.xml',
        'report/product_eff_summary.xml',
        'report/unit_weight_tolerance_report.xml',
        'report/unit_weight_tolerance_summary.xml',
        'report/production_delay_report.xml',
        'report/production_delay_summary.xml',
        'report/machine_data_report.xml',
        'report/production_delay_report_template.xml',
        "report/production_completion_memo_report_template.xml",
        'report/raw_material_issue_chit_template.xml',
        "views/power_consumption_views.xml",
        'report/power_consumption_analysis_report.xml',
    ],
    "assets": {
        "web.assets_backend": [
            "starplastic_work_center/static/src/js/control_panel_patch.js",
            "starplastic_work_center/static/src/xml/control_panel_inherit.xml",
            "starplastic_work_center/static/src/js/power_matrix.js",
            "starplastic_work_center/static/src/xml/power_matrix_template.xml",
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
